import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import * as THREE from 'three';
import { createSpeechEngine, createProviderTTSAdapter } from '../src/speech';
import type { FrameScheduler } from '../src/speech';
import { visemeTap } from '../src/core';
import { createMotionEngine } from '../src/motion';
import {
  RIG_VISEME_MORPHS,
  type AudioEngine,
  type LoadedAvatar,
  type MotionEngine,
  type SpeechEngine,
  type VisemeFrame,
} from '../src/contracts';
// Committed, dev-only fixture (Polly-shaped speech marks) generated by
// tools/asset-pipeline/gen-viseme-fixture.ts from espeak-ng timings.
import fixtureRaw from './fixtures/viseme-polly-hello.jsonl?raw';

/**
 * Standard Polly en-US viseme symbol -> canonical hologlyph viseme morph.
 * Kept in the test only (never in shipped src). Only Polly `sil` maps to
 * viseme_sil; the schwa `@` folds into viseme_aa (Oculus-style AA grouping),
 * and every other Polly symbol hits a distinct canonical mouth morph. Polly
 * has no `nn` symbol, so viseme_nn is UNREACHABLE through this path and is
 * asserted never to be driven.
 */
const POLLY_TO_CANONICAL: Record<string, string> = {
  sil: 'viseme_sil',
  p: 'viseme_pp',
  t: 'viseme_dd',
  S: 'viseme_ch',
  T: 'viseme_th',
  f: 'viseme_ff',
  k: 'viseme_kk',
  i: 'viseme_ih',
  r: 'viseme_rr',
  s: 'viseme_ss',
  u: 'viseme_ou',
  '@': 'viseme_aa',
  a: 'viseme_aa',
  e: 'viseme_ee',
  E: 'viseme_ee',
  o: 'viseme_oh',
  O: 'viseme_oh',
};

interface PollyMark {
  time: number;
  type: 'viseme';
  value: string;
}

const REACHABLE_CANONICAL = RIG_VISEME_MORPHS.filter((m) => m !== 'viseme_nn');

function parseFixture(): PollyMark[] {
  return fixtureRaw
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line) => JSON.parse(line) as PollyMark);
}

function makeAvatar(): LoadedAvatar {
  const root = new THREE.Group();
  const head = new THREE.Bone();
  head.name = 'head';
  const morphStore: Record<string, number> = {};
  return {
    root,
    morphMeshes: [],
    animations: [],
    bones: { head },
    setMorph(name: string, w: number) {
      morphStore[name] = Math.min(1, Math.max(0, w));
    },
    getMorph(name: string) {
      return morphStore[name] ?? 0;
    },
    dispose() {},
  };
}

function makeFakeAudio(): AudioEngine {
  return {
    context: null,
    resumeFromGesture: async () => {},
    connectElement: () => {},
    disconnectElement: () => {},
    readEnergy: () => 0,
    suspend: () => {},
    dispose: () => {},
  };
}

class FakeAudioElement {
  src = '';
  currentTime = 0;
  private readonly _listeners = new Map<string, Array<() => void>>();
  play(): Promise<void> {
    return Promise.resolve();
  }
  pause(): void {}
  load(): void {}
  removeAttribute(): void {}
  addEventListener(type: string, fn: () => void): void {
    const list = this._listeners.get(type) ?? [];
    list.push(fn);
    this._listeners.set(type, list);
  }
  emit(type: string): void {
    for (const fn of this._listeners.get(type) ?? []) fn();
  }
}

let lastAudio: FakeAudioElement | null = null;
const FakeAudioCtor = class extends FakeAudioElement {
  constructor(src?: string) {
    super();
    if (src) this.src = src;
    lastAudio = this;
  }
};

class ManualScheduler implements FrameScheduler {
  private readonly _cbs: Array<() => void> = [];
  start(callback: () => void): () => void {
    this._cbs.push(callback);
    return () => {
      const idx = this._cbs.indexOf(callback);
      if (idx >= 0) this._cbs.splice(idx, 1);
    };
  }
  tick(): void {
    for (const cb of [...this._cbs]) cb();
  }
}

interface Seam {
  avatar: LoadedAvatar;
  motion: MotionEngine;
  scheduler: ManualScheduler;
  engine: SpeechEngine;
}

function setupSeam(visemes: VisemeFrame[]): Seam {
  const avatar = makeAvatar();
  const motion = createMotionEngine();
  motion.attach(avatar);
  const scheduler = new ManualScheduler();
  const adapter = createProviderTTSAdapter({
    synthesize: async () => ({ audioUrl: 'mock', visemes }),
    scheduler,
  });
  const engine = createSpeechEngine(makeFakeAudio());
  // Mirror the production seam: route adapter viseme events into the motion sink.
  engine.setAdapter(visemeTap(adapter, (f) => motion.applyVisemeFrame(f), () => {}));
  return { avatar, motion, scheduler, engine };
}

async function flushMicrotasks(): Promise<void> {
  await Promise.resolve();
  await Promise.resolve();
}

/**
 * Play `frames` through the seam at their REAL timestamps: each frame is
 * applied, then motion advances in 16 ms steps only until the next frame's
 * timestamp (final frame gets a defined `finalHold`). Mouth weights are
 * attack/release smoothed (tau_attack 0.05 s), so peaks reflect what real
 * playback would show, not an instant snap. Returns the per-morph peak.
 */
function playFrames(
  seam: Pick<Seam, 'avatar' | 'motion' | 'scheduler'>,
  frames: VisemeFrame[],
  audio: { currentTime: number },
  finalHold = 0.1,
): Record<string, number> {
  const maxWeight: Record<string, number> = {};
  const DT = 0.016;
  for (let i = 0; i < frames.length; i++) {
    const frame = frames[i]!;
    audio.currentTime = frame.time;
    seam.scheduler.tick();
    const windowEnd = i + 1 < frames.length ? frames[i + 1]!.time : frame.time + finalHold;
    for (let t = frame.time; t < windowEnd; ) {
      const stepDt = Math.min(DT, windowEnd - t);
      seam.motion.update(stepDt, t);
      t += stepDt;
      for (const name of RIG_VISEME_MORPHS) {
        maxWeight[name] = Math.max(maxWeight[name] ?? 0, seam.avatar.getMorph(name));
      }
    }
  }
  return maxWeight;
}

describe('viseme end-to-end (speech -> motion)', () => {
  beforeEach(() => {
    lastAudio = null;
    vi.stubGlobal('Audio', FakeAudioCtor);
  });
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('Polly speech-mark fixture drives reachable visemes through the provider seam', async () => {
    const marks = parseFixture();
    // The fixture must exercise exactly the 14 Polly-reachable canonical visemes.
    const fixtureCanonicals = [...new Set(marks.map((m) => POLLY_TO_CANONICAL[m.value]!))];
    expect(fixtureCanonicals.sort()).toEqual([...REACHABLE_CANONICAL].sort());
    expect(fixtureCanonicals).not.toContain('viseme_nn');

    const frames: VisemeFrame[] = marks.map((m) => ({
      time: m.time / 1000,
      weights: { [POLLY_TO_CANONICAL[m.value]!]: 1 },
    }));

    const { avatar, motion, scheduler, engine } = setupSeam(frames);
    const done = engine.speak('Papa ate a red cat. Go thought. The boy saw two blue shoes.');
    await flushMicrotasks();
    expect(lastAudio).not.toBeNull();

    // Real Polly timings include phones as short as ~33 ms; with attack
    // smoothing such a phone honestly peaks well below 1. The contract here
    // is that every reachable canonical morph visibly activates at real
    // timing, and the unreachable one never does.
    const maxWeight = playFrames({ avatar, motion, scheduler }, frames, lastAudio!);

    lastAudio!.emit('ended');
    await done;

    for (const canonical of REACHABLE_CANONICAL) {
      expect(maxWeight[canonical] ?? 0).toBeGreaterThan(0.3);
    }
    // Polly has no nn symbol, so this path must never drive it.
    expect(maxWeight['viseme_nn'] ?? 0).toBe(0);
  });

  it('canonical VisemeFrame timeline drives all 15 visemes', async () => {
    const frames: VisemeFrame[] = RIG_VISEME_MORPHS.map((morph, i) => ({
      time: i * 0.1,
      weights: { [morph]: 1 },
    }));

    const { avatar, motion, scheduler, engine } = setupSeam(frames);
    const done = engine.speak('canonical timeline');
    await flushMicrotasks();
    expect(lastAudio).not.toBeNull();

    // 100 ms per viseme at real playback stepping converges to ~0.85 under
    // attack smoothing (1 - exp(-0.096/0.05)); assert a strong activation.
    const maxWeight = playFrames({ avatar, motion, scheduler }, frames, lastAudio!);

    lastAudio!.emit('ended');
    await done;

    for (const morph of RIG_VISEME_MORPHS.filter((m) => m !== 'viseme_nn')) {
      expect(maxWeight[morph] ?? 0).toBeGreaterThan(0.8);
    }
    // The gap closes: viseme_nn is reachable through the canonical timeline.
    expect(maxWeight['viseme_nn'] ?? 0).toBeGreaterThan(0.8);
  });
});
